spring.application.name=taskwave

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://admin:admin@taskwave.09gwvsc.mongodb.net/taskwave?appName=TaskWave&retryWrites=true&w=majority

# JWT Configuration
app.jwt.secret=YWJjYXNoYWtxdXdhbnhoYWthamFoYWphaGFuYWJ4dmI=
app.jwt.expiration=86400000

# Server
server.port=8080
